/**
 * Worker Configuration Guard
 *
 * Blocks agents from manually creating or modifying worker-configuration.d.ts.
 * That file is generated by Cloudflare Wrangler and should be regenerated with
 * `wrangler types` instead of hand-edited via write/edit or shell redirection.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { isToolCallEventType } from "@earendil-works/pi-coding-agent";

const PROTECTED_FILE = "worker-configuration.d.ts";

const BLOCK_REASON =
	`BLOCKED: ${PROTECTED_FILE} is generated and must not be manually ` +
	"created, edited, deleted, or overwritten by an agent. Run `wrangler types` " +
	"from the worker project to regenerate it instead.";

const PROTECTED_FILE_RE = /(?:^|[^\w.-])worker-configuration\.d\.ts(?:$|[^\w.-])/;
const PROTECTED_FILE_OUTPUT_REDIRECTION_RE =
	/(?:^|\s)(?:\d*)>{1,2}\s*["']?(?:[^\s"']*\/)?worker-configuration\.d\.ts["']?(?:$|\s)/;
const HARMLESS_STDIO_REDIRECTION_RE = /\s+\d?>&\d\b/g;
const BASH_MUTATION_RE =
	/\b(?:tee|touch|cp|mv|rm|install|truncate|dd|rsync|python|python3|node|deno|ruby|bun|tsx|ts-node)\b|\b(?:sed|perl)\b[^\n]*(?:-i|--in-place)\b|\bgit\s+(?:checkout|restore|reset)\b/;
const SHELL_META_RE = /[;&|<>`]/;
const WRANGLER_TYPES_ONLY_RE =
	/^\s*(?:(?:env|export)\s+[^\s]+\s+)*((?:\.\/node_modules\/\.bin\/)?wrangler|(?:npx|bunx)\s+wrangler|(?:npm|pnpm|yarn|bun)\s+(?:exec\s+|dlx\s+)?wrangler)\s+types(?:\s+[^;&|<>`]*)?\s*$/;

function normalizeToolPath(path: string): string {
	return path.replace(/^@/, "").replaceAll("\\", "/");
}

function isProtectedPath(path: unknown): boolean {
	if (typeof path !== "string") return false;
	const normalized = normalizeToolPath(path);
	return normalized.split("/").at(-1) === PROTECTED_FILE;
}

function referencesProtectedFile(command: string): boolean {
	return PROTECTED_FILE_RE.test(command);
}

function isWranglerTypesOnly(segment: string): boolean {
	const normalized = segment.replace(HARMLESS_STDIO_REDIRECTION_RE, "").trim();
	return !SHELL_META_RE.test(normalized) && WRANGLER_TYPES_ONLY_RE.test(normalized);
}

// Splits on top-level command separators (&&, ||, ;, &, |) so a compound command
// like `wrangler types && tsc --noEmit` or `cd worker && wrangler types` is judged
// segment-by-segment instead of failing the all-or-nothing "pure wrangler types"
// check just because it isn't the *only* thing on the line.
function splitCommandSegments(command: string): string[] {
	return command
		.replace(/\\\n/g, " ")
		.split(/\|\||&&|[;&|]/)
		.map((segment) => segment.trim())
		.filter(Boolean);
}

function segmentMutatesProtectedFile(segment: string): boolean {
	if (!referencesProtectedFile(segment)) return false;
	if (isWranglerTypesOnly(segment)) return false;

	return PROTECTED_FILE_OUTPUT_REDIRECTION_RE.test(segment) || BASH_MUTATION_RE.test(segment);
}

function appearsToModifyProtectedFile(command: string): boolean {
	return splitCommandSegments(command).some(segmentMutatesProtectedFile);
}

export default function (pi: ExtensionAPI) {
	pi.on("tool_call", (event, ctx) => {
		if (isToolCallEventType("write", event) || isToolCallEventType("edit", event)) {
			if (isProtectedPath(event.input.path)) {
				if (ctx.hasUI) {
					ctx.ui.notify(`Blocked manual change to ${PROTECTED_FILE}; run wrangler types.`, "warning");
				}
				return { block: true, reason: BLOCK_REASON };
			}

			return;
		}

		if (!isToolCallEventType("bash", event)) return;
		if (!appearsToModifyProtectedFile(event.input.command)) return;

		if (ctx.hasUI) {
			ctx.ui.notify(`Blocked manual change to ${PROTECTED_FILE}; run wrangler types.`, "warning");
		}
		return { block: true, reason: BLOCK_REASON };
	});
}
